# -*- coding: utf-8 -*-
"""asemblyai.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1kLaN6o7ZdvGoZwPRI-JA4gvr1t7av3sz
"""

!pip install streamlit
!pip install pandas
!pip install numpy
!npm install -g localtunnel

import numpy as np
import pandas as pd
import streamlit as st
import subprocess

# Set up Streamlit app
st.title("Analytics Dashboard")

# Create a sidebar for user input
st.sidebar.header("User Input")
selected_metric = st.sidebar.selectbox("Select a Metric", ["Sales", "Profit", "Revenue"])
selected_year = st.sidebar.slider("Select a Year", 2015, 2021, 2019)

# Generate some random data based on user input
data = pd.DataFrame(np.random.randint(0, 100, size=(100, 3)), columns=["Sales", "Profit", "Revenue"])
data["Year"] = np.random.randint(selected_year - 2, selected_year + 2, size=100)

# Filter the data based on user input
filtered_data = data[data["Year"] == selected_year][[selected_metric]]

# Display the filtered data in a chart and a table
st.header("Filtered Data")
st.write(filtered_data)
st.line_chart(filtered_data)

# Generate a shareable URL using LocalTunnel
tunnel = subprocess.Popen(["lt", "--port", "8501"], stdout=subprocess.PIPE)
url = tunnel.stdout.readline().decode("utf-8").strip()
st.write("Shareable URL:", url)